### ISSUE TITLE
No Error but no completed Results of the web example

### ISSUE THREAD

**Issue by AbbasiAYE** [fjxmlzn/DoppelGANger#10]
Hello Zinan,

I tried to run all examples together, "google", "web", "FCC_MBA", but it seems that they require extremely large RAM. 
Then I tried to run only "web" with very computationally not demanding parameters, such as below. 

However, as you see in the attached file, the simulation stops at 12%.... 

Why am I not able to run until the end? the simulation probably exists because of processing time exceeded, but as you see in the file, there is no output error (all warning)...
My node: is 32 G RAM and 4 cores

Not demanding parameters for web example:
        {
            "dataset": ["web"],
            "epoch": [50],#def [400],
            "run": [0],# def [0, 1, 2],
            "sample_len": [10],# def[1, 5, 10, 25, 50],
            "extra_checkpoint_freq": [5],
            "epoch_checkpoint_freq": [1],
            "aux_disc": [True],
            "self_norm": [True]
        },

[worker.log](https://github.com/fjxmlzn/DoppelGANger/files/5438799/worker.log)

**Comment by fjxmlzn** [comment]
I have never seen this problem before. Could you help me check if the process is still there when it gets stuck? And does it get stuck at the same point (12%) every time you run the code?

**Comment by fjxmlzn** [comment]
I'll close the issue now. Feel free to reopen it if the problem persists.

**Comment by AbbasiAYE** [comment]
Sure, thanks
I haven't solved it yet, but could not find the time to work on it neither...
