### ISSUE TITLE
Error in summary.merge function

### ISSUE THREAD

**Issue by AbbasiAYE** [fjxmlzn/DoppelGANger#11]
Hi Zinan Lin

I've been trying to run this on TF2 for a bit now, after chaning many lines from TF1 to TF2. I reached this point... any help is appreciated...

Traceback (most recent call last):
  File "/opt/conda/bin/start_gpu_task", line 11, in <module>
    load_entry_point('GPUTaskScheduler', 'console_scripts', 'start_gpu_task')()
  File "/home/jovyan/GAN2/DoppelGANger/GPUTaskScheduler/gpu_task_scheduler/start_gpu_task.py", line 23, in main
    worker.main()
  File "/home/jovyan/GAN2/DoppelGANger/example_training/gan_task.py", line 120, in main
    gan.build()
  File "../gan/doppelganger.py", line 213, in build
    self.build_summary()
  File "../gan/doppelganger.py", line 516, in build_summary
    self.g_summary = tf.compat.v1.summary.merge(self.g_summary)
  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/summary/summary.py", line 371, in merge
    val = _gen_logging_ops.merge_summary(inputs=inputs, name=name)  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/ops/gen_logging_ops.py", line 468, in merge_summary    "MergeSummary", inputs=inputs, name=name)  File "/opt/conda/lib/python3.7/site-packages/tensorflow/python/framework/op_def_library.py", line 436, in _apply_op_helper    (prefix, dtype.name))TypeError: Tensors in list passed to 'inputs' of 'MergeSummary' Op have types [bool, bool, bool] that do not match expected type string.

**Comment by fjxmlzn** [comment]
The code was developed on TF1. Running it with TF2 requires many changes. I do not know what changes you have made so it is hard for me the make sense of this error. Would you mind providing all the codes you modified?

Thanks!

**Comment by AbbasiAYE** [comment]
Its ok, thanks, issue solved.

Just a question out of curiosity, how long does the simulation run? how many GPUs do you usually use?

Thanks

**Comment by fjxmlzn** [comment]
Great!

For each experiment (one combination of the hyper-parameters), it takes less than ~72 hours to finish on 1 NVIDIA Tesla P100 GPU.
