### ISSUE TITLE
Large dimensionality of the attributes (metadata) and possible alternatives to realize synthetic time series generation "translated" from real measured time series?

### ISSUE THREAD

**Issue by 89ng** [fjxmlzn/DoppelGANger#13]
Thank you so much for such great work! I have experimented with this novel GAN model and it works very well on some exemplary datasets.  Whereas since my subsequent research capitalizing on synthetic data generation is mainly on urban local climate prediction, the types of attributes (metadata) seem to be very different, and I am really still a novice to the deep learning community especially regarding time series, so I would like to ask:

- **Is that possible that I use one image (maybe vectorized by each pixel) as an attribute? I guess the major concern is the size of the image might lead to very high dimensions (maybe hundreds to thousands of pixels).** I've also noticed  you mentioned in the paper, " When the total dimension of samples (measurements + metadata) is large, judging sample fidelity is hard." And thus you added an auxiliary discriminator for attributes generated. Based on this argument could I assume that current architecture is already able to handle some high-dimensional inputs? Otherwise is there any rule of thumb that tells the highest "safe" dimensionality? Then I could prepare the training data with respect to this. 
- **Is that possible to generate synthetic time series based on some measured time series**? In my case measured time series could be weather data from the meteorological station nearby while synthetic ones could be actual weather data in a specific scenario. In this task, these time series usually have the same length, so it might be comparable to a "data augmentation" from the measured data or maybe comparable to the "image style translation" task but implemented on time series. One intuitive solution I could come up with is to use all these measured time series as a high-dimensional attribute (the length of annual hourly time series is usually 8760), but it might again lead to the aforementioned high-dimension issue.

Since currently I need to prepare the training data according to the characteristics of DoppelGANer and it will be a very nasty and time-consuming process, I still could not answer these questions with my own experiments, sorry if I was too tedious with my case. Any suggestions or insights related to my questions will be appreciated. Thank you so much in advance!

**Comment by fjxmlzn** [comment]
Thank you for your interest in DoppelGANger! I understand that your question is about whether DoppelGANger would work for high-dimensional metadata. We did not test it for such high-dimension metadata you mentioned, so I don't have enough evidence to give you an accurate answer. On the high level what you plan to use DoppelGANGer makes sense to me, but I would suspect that you will need to change the network architecture and increase the model size a little bit. For example, the current metadata generator and discriminator are shallow MLPs, which I don't think will work well for images (i.e., the first case you said). Changing the metadata generator and discriminator to deeper CNNs or other more complicated architectures that people are using for images should give better results.

**Comment by 89ng** [comment]
Hi Zinan,

Thank you so much for your patient reply! I will follow your suggestion and try to adjust the architecture a bit. I hope it finally works on my case and will report to you then haha.

Best,
