### ISSUE TITLE
Real Valued Time Series with no attributes

### ISSUE THREAD

**Issue by AnkurDebnath35** [fjxmlzn/DoppelGANger#16]
Hi,

I have been meaning to test out this model for generation of real valued time series only, with no "attributes"(categorical). Is it even possible?

Thanks in advance !

**Comment by fjxmlzn** [comment]
Sorry that we didn't directly provide such functionality at this point. There are two workarounds: you can either provide a dummy attribute with constant or random values; or modify the code (delete the meta generator part).
