### ISSUE TITLE
How to pre-specify the length of features

### ISSUE THREAD

**Issue by 89ng** [fjxmlzn/DoppelGANger#17]
Thank you for the great work again! Now since I just have a small amount of training data with fixed length, I would like to pre-specify the length of features to reduce the difficulty of training a bit, but I have no clue how to do that. I noticed in issue #7 [https://github.com/fjxmlzn/DoppelGANger/issues/7](url), you mentioned it could be achieved via minor code change, could you please give me some suggestions on how to do so? Thank you so much in advance!

**Comment by fjxmlzn** [comment]
You will need to overwrite cur_gen_flag https://github.com/fjxmlzn/DoppelGANger/blob/ab2d20e48a30bcf44aab98e9ec419cd68f1195e6/gan/network.py#L400 with ones, so that the network will ignore generation flags and keep generating till the maximum length.
