### ISSUE TITLE
membership_inference_attack

### ISSUE THREAD

**Issue by fxctydfty** [fjxmlzn/DoppelGANger#24]
Hey,
I am trying to reproduce the Figure-15. Is it possible to share the source code for membership inference attacks from your paper. 
Thanks in advance for your help.

**Comment by fjxmlzn** [comment]
This is the code snippet is here

```
# After GAN is trained

# Load the final checkpoint
gan.load()

# train_data_feature, train_data_attribute are loaded from https://github.com/fjxmlzn/DoppelGANger/blob/e732a4d077ba1504e6e401df9c2d1048c8efb2a9/example_training/gan_task.py#L20-L45 
d_train = gan.discriminate_from(
    [train_data_feature], [train_data_attribute])

# test_data_feature, test_data_attribute are loaded by the same way, except passing flag="test" to load_data
d_test = gan.discriminate_from(
    [test_data_feature], [test_data_attribute])

num_train = train_data_feature.shape[0]

sort_id = np.argsort(list(d_train) + list(d_test))[::-1]

acc = np.where(sort_id[0: num_train] < num_train)[0].shape[0] / float(num_train)
```

**Comment by fxctydfty** [comment]
What is "acc" meaning here?

**Comment by fjxmlzn** [comment]
The attack accuracy, y-axis of Figure 15

**Comment by fxctydfty** [comment]
Thanks.

**Comment by fxctydfty** [comment]
Hey,
I need some help.
I understand from here `# train_data_feature, train_data_attribute are loaded from https://github.com/fjxmlzn/DoppelGANger/blob/e732a4d077ba1504e6e401df9c2d1048c8efb2a9/example_training/gan_task.py#L20-L45 `
Could you please explain little bit before that like, "load and call DoppleGANger".
Thanks for your help.

**Comment by fjxmlzn** [comment]
What I meant is that you can just append these codes at the end of  https://github.com/fjxmlzn/DoppelGANger/blob/master/example_training/gan_task.py, where DoppelGANger is trained
