### ISSUE TITLE
CLI getting stuck on running example_training/main.py

### ISSUE THREAD

**Issue by NitishG20** [fjxmlzn/DoppelGANger#25]
Hey, I am trying to run the example training with GPU on Windows 10 with python 3.6 and tf 1.4. On trying it run with verbose, the last part before it gets stuck is this:
`import 'pathos.secure.copier' # <_frozen_importlib_external.SourceFileLoader object at 0x000001D083E1C9B0>
# C:\Users\e106923\Miniconda3\envs\DGAN\lib\site-packages\pathos-0.2.8-py3.6.egg\pathos\secure\__pycache__\tunnel.cpython-36.pyc matches C:\Users\e106923\Miniconda3\envs\DGAN\lib\site-packages\pathos-0.2.8-py3.6.egg\pathos\secure\tunnel.py
# code object from 'C:\\Users\\e106923\\Miniconda3\\envs\\DGAN\\lib\\site-packages\\pathos-0.2.8-py3.6.egg\\pathos\\secure\\__pycache__\\tunnel.cpython-36.pyc'
import 'pathos.secure.tunnel' # <_frozen_importlib_external.SourceFileLoader object at 0x000001D083E1CC88>
import 'pathos.secure' # <_frozen_importlib_external.SourceFileLoader object at 0x000001D083E1C6A0>
import 'pathos' # <_frozen_importlib_external.SourceFileLoader object at 0x000001D083DA56D8>
import 'gpu_task_scheduler.gpu_task_scheduler' # <_frozen_importlib_external.SourceFileLoader object at 0x000001D083CA1D68>
# C:\Users\e106923\Miniconda3\envs\DGAN\DoppelGANger-master\example_training\__pycache__\gan_task.cpython-36.pyc matches C:\Users\e106923\Miniconda3\envs\DGAN\DoppelGANger-master\example_training\gan_task.py
# code object from 'C:\\Users\\e106923\\Miniconda3\\envs\\DGAN\\DoppelGANger-master\\example_training\\__pycache__\\gan_task.cpython-36.pyc'
# C:\Users\e106923\Miniconda3\envs\DGAN\lib\site-packages\gputaskscheduler-0.1.0-py3.6.egg\gpu_task_scheduler\__pycache__\gpu_task.cpython-36.pyc matches C:\Users\e106923\Miniconda3\envs\DGAN\lib\site-packages\gputaskscheduler-0.1.0-py3.6.egg\gpu_task_scheduler\gpu_task.py
# code object from 'C:\\Users\\e106923\\Miniconda3\\envs\\DGAN\\lib\\site-packages\\gputaskscheduler-0.1.0-py3.6.egg\\gpu_task_scheduler\\__pycache__\\gpu_task.cpython-36.pyc'
import 'gpu_task_scheduler.gpu_task' # <_frozen_importlib_external.SourceFileLoader object at 0x000001D083E26780>
import 'gan_task' # <_frozen_importlib_external.SourceFileLoader object at 0x000001D083E26208>
# C:\Users\e106923\Miniconda3\envs\DGAN\lib\__pycache__\hmac.cpython-36.pyc matches C:\Users\e106923\Miniconda3\envs\DGAN\lib\hmac.py
# code object from 'C:\\Users\\e106923\\Miniconda3\\envs\\DGAN\\lib\\__pycache__\\hmac.cpython-36.pyc'
import 'hmac' # <_frozen_importlib_external.SourceFileLoader object at 0x000001D083E266A0>`

I can't seem to figure out what's the issue as there is no error but no output.

**Comment by fjxmlzn** [comment]
Sorry that I missed this comment earlier. Would you mind sharing the complete console output when running example_training/main.py? Thanks!

**Comment by fjxmlzn** [comment]
Feel free to reopen the issue if you still have problems with it
