### ISSUE TITLE
Dynamic attributes / attributes with time stamp?

### ISSUE THREAD

**Issue by 89ng** [fjxmlzn/DoppelGANger#26]
Thank you so much for this nice work again! I have a question about the attribute (metadata) generator, is that possible to generate attributes with timestamps (dynamic attributes), since it seems in the papers it should be an MLP that only generates static attributes? Or are there any other approaches that we could input these dynamic attributes as conditions to generate features? The attributes might have the same length and timestamps as the features.

The question mainly arose from the technical blog you posted on this repository: Hazy: (2)[Generating Synthetic Sequential Data using GANs](https://medium.com/towards-artificial-intelligence/generating-synthetic-sequential-data-using-gans-a1d67a7752ac). In the second example, the author uses such kind of dynamic attribute, like hourly weather data. I also asked the author of the blog about the implementation details, yet still did not get replied.

**Comment by fjxmlzn** [comment]
If the 'dynamic attributes' have the same length as features, you can just put them as part of features. Note that 'features' in the code can be multi-dimension and can be mixed with categorical and continuous ones, so it should be flexible enough for you to model those 'dynamic attributes'.

**Comment by 89ng** [comment]
Thank you so much for your kind reply! Indeed it should be an option, but in this case, how could I use these dynamic attributes as conditions to guide the conditional generation?

**Comment by fjxmlzn** [comment]
The 'dynamic attributes' will then be generated jointly with features; so ideally the correlations between 'dynamic attributes'  and features can still be learned. Or do you mean that you want to generate features according to specific given 'dynamic attributes'?

**Comment by 89ng** [comment]
Yes, ideally I want to generate features according to specific given 'dynamic attributes', is that possible?

**Comment by fjxmlzn** [comment]
I see. It is not possible with this architecture then. The other option is that you pad the 'dynamic attributes' to the same length, and treat that as normal attributes so that you can generate features according to it. (But training might be hard if the total dimension of those 'dynamic attributes' is large.)

**Comment by 89ng** [comment]
All right, I think learning a joint distribution could already be very helpful, I will try to modify my problem to see whether it could fit current architecture, thanks a lot!
