### ISSUE TITLE
Request for min/max used for feature and attribute normalization in input data

### ISSUE THREAD

**Issue by lipikaramaswamy** [fjxmlzn/DoppelGANger#27]
Hello, I see the input datasets you've shared in [drive](https://drive.google.com/drive/folders/14x5f4Q34mlyZbDjADT8jbuOrgWyuUjFV) have been normalized. Would you be able to provide the min/max used scaling for each feature and attribute so an inverse transform can be applied to get samples back in the original scale? Thanks!

**Comment by fjxmlzn** [comment]
Sorry for the delay. 

The link you put is Wikipedia web traffic dataset. Following is the information about it.


For features, we  first do `x -> log(1 + x)` transform, and then normalize the data to `[-1, 1]` range according to the global `min=0` and `max=18.02413958371087` (i.e., `data -> data / max * 2 - 1`). You can do the inverse transform accordingly.


For the three attributes (domain, access type, agent), the meaning for the indexes (i.e., 0 ~ 8 for domain, 0 ~ 2 for access type, and 0 ~ 1 for agent) are:
```
Projects:  ['commons.wikimedia.org', 'de.wikipedia.org', 'en.wikipedia.org', 'es.wikipedia.org', 'fr.wikipedia.org', 'ja.wikipedia.org', 'ru.wikipedia.org', 'www.mediawiki.org', 'zh.wikipedia.org']
Access:  ['all-access', 'desktop', 'mobile-web']
Agents:  ['all-agents', 'spider']
```

**Comment by lipikaramaswamy** [comment]
Thank you! Appreciate the detail.
