### ISSUE TITLE
The data generated ranges from 0 to 2

### ISSUE THREAD

**Issue by GuarderS** [fjxmlzn/DoppelGANger#28]
The trained model produces data in the range of [0-2], which I cannot restore to its original size by multiplying a value. Do you know what caused it? ( I guess the range should be [0-1])
![image](https://user-images.githubusercontent.com/41230192/147095688-72815dca-1fab-4555-a0b8-7de523270d96.png)

**Comment by fjxmlzn** [comment]
Would you mind providing more details, e.g., the hyper-parameters, and what the original data looks like?

**Comment by GuarderS** [comment]
感谢您能回复我，我访问了您的主页，发现您是清华大佬，如果不介意的话我想用中文来描述，可能比较准确一点。
**date_attribute_outputs and data_feature_outputs:** 
![image](https://user-images.githubusercontent.com/41230192/147170191-6fcac503-64a4-43e7-ad1d-e60424b36528.png)

**data_attribute:**
![image](https://user-images.githubusercontent.com/41230192/147170407-8920081b-1c17-42e9-8b2d-59ffff7af4e9.png)

**data_feature:**
![image](https://user-images.githubusercontent.com/41230192/147170517-4de7c82f-ceb5-46d2-b11b-4543bbbc6b96.png)

**我在两个地方改动了参数，第一个是example_train里面的config：**
![image](https://user-images.githubusercontent.com/41230192/147170715-a4ff4ae2-fc2b-4913-8361-baa833407d3e.png)

**第二个是example_generate_data里面的config_generate_data：**
![image](https://user-images.githubusercontent.com/41230192/147171328-e81cf598-df2c-4d37-aaa6-5335d23bde92.png)

date_attribute是五维的代表五种事件，data_feature是二维的，分别是纬度和经度，除以一个数使其范围变成了0-1。

**Comment by GuarderS** [comment]
如果可以的话，我们可以邮件联系吗 PS: MU1758922095@163.com
