### ISSUE TITLE
unreasonable output

### ISSUE THREAD

**Issue by JimmyZhan1213** [fjxmlzn/DoppelGANger#32]
I run the main.py file under example_training(without_GPUTaskScheduler), the training process is no problem. However, when I run main.py under example_training on Windows, in tensorflow1, the project has no output and no error message, so I tried it in the environment of tensorflow2, and finally generated a results folder, which contains a lot of running information, but the worker.log and generate.log under each folder prompt the following: 'start_gpu_task' is not an internal or external command, nor is it a runnable program or batch file. I would like to ask if there is a reason or a solution to this situation?
![image](https://user-images.githubusercontent.com/92135239/188180288-1b743896-d4fc-4753-98e0-a65addeecc2a.png)
![image](https://user-images.githubusercontent.com/92135239/188180448-02c19d3c-ddf7-4967-a46e-5a39c4dd281a.png)
![image](https://user-images.githubusercontent.com/92135239/188180574-a9ccbf97-2ffd-4e2e-8c9d-fe7c16e04840.png)
![image](https://user-images.githubusercontent.com/92135239/188180615-71bab9c3-ac5b-47da-8bcb-bb56f5b5dc7f.png)
![image](https://user-images.githubusercontent.com/92135239/188180654-8503ece6-5b1c-4b4f-86d6-3ac4c6558a01.png)
![image](https://user-images.githubusercontent.com/92135239/188180726-e15ffed9-b900-4022-a5db-b6158a402a61.png)

**Comment by fjxmlzn** [comment]
How did you install the Python environment and how did you install https://github.com/fjxmlzn/GPUTaskScheduler? start_gpu_task should be available after GPUTaskScheduler is installed

**Comment by JimmyZhan1213** [comment]
First, I created a DGtf2 environment of python3.7.12 and tensorflow-gpu2.1.0 under anaconda, and then downloaded GPUTaskScheduler and installed it, an error will be reported. I put the folder under example_training and installed it with pip install -e GPUTaskScheduler, and the above mentioned to the result.
![image](https://user-images.githubusercontent.com/92135239/188251169-e6a419f7-d45c-4f0f-8edc-06556ea94978.png)
![image](https://user-images.githubusercontent.com/92135239/188251649-269d0e95-a432-4f85-a4a8-98d28f0bca4e.png)

**Comment by fjxmlzn** [comment]
Thanks for the info! 

Would you mind sending me an email zinanl AT andrew.cmu.edu?  We can debug it there. Thanks!

**Comment by JimmyZhan1213** [comment]
certainly! thanks for your help!

**Comment by H4Njx** [comment]
https://github.com/fjxmlzn/DoppelGANger/issues/32#issuecomment-1236025272
@Ezioooooo 
here is the GPUTaskScheduler install guide:
step 1. git clone https://github.com/fjxmlzn/GPUTaskScheduler.git
step 2. cd GPUTaskScheduler && pip install -e .

**Comment by fjxmlzn** [comment]
Closing this issue since it was resolved after installing the libraries correctly.
