### ISSUE TITLE
About two MLPs

### ISSUE THREAD

**Issue by Happyhappyhappy23** [fjxmlzn/DoppelGANger#34]
<img width="441" alt="image" src="https://user-images.githubusercontent.com/39253803/213906518-cdbce060-8759-4241-8aef-5c6153f28167.png">

Is there actually only one MLP in the code? "Real" and "fake" metadata are generated at the same time?

**Comment by fjxmlzn** [comment]
Sorry, I don't fully get your question. The screenshot in the paper that you attached is exactly what we did. The corresponding code is in this function https://github.com/fjxmlzn/DoppelGANger/blob/1e16b4e023f5ed4e5b82e878d4896d40eaf097b9/gan/network.py#L170

**Comment by GHY18** [comment]
> Sorry, I don't fully get your question. The screenshot in the paper that you attached is exactly what we did. The corresponding code is in this function
> 
> https://github.com/fjxmlzn/DoppelGANger/blob/1e16b4e023f5ed4e5b82e878d4896d40eaf097b9/gan/network.py#L170

<img width="257" alt="image" src="https://user-images.githubusercontent.com/39253803/213907054-690d4893-0aa1-479c-996c-60b18d037d0d.png">
Is this concatenated together and fed into the MLP?

**Comment by GHY18** [comment]
Sorry I didn't understand the code above well. Could you please explain it in more detail? Thank you so much!
