### ISSUE TITLE
Training does not run although the input is of the required form

### ISSUE THREAD

**Issue by dgtriantis** [fjxmlzn/DoppelGANger#37]
Hello, I'm trying to run the TF2 version of DoppleGANger but I'm running into some issues. 
I have transformed the input data in the form that is required (according to  README). When trying to train the GAN I run into the following error:

Traceback (most recent call last):
  File "C:\Users\dgtri\Desktop\DoppelGANger-TF2\example_training(wt)\main.py", line 29, in <module>
    normalize_per_sample(
  File "C:\Users\dgtri\Desktop\DoppelGANger-TF2\example_training(wt)\..\gan\util.py", line 182, in normalize_per_sample
    additional_attribute = np.stack(additional_attribute, axis=1)
  File "<__array_function__ internals>", line 5, in stack
  File "C:\Users\dgtri\anaconda3\lib\site-packages\numpy\core\shape_base.py", line 423, in stack
    raise ValueError('need at least one array to stack')
ValueError: need at least one array to stack

I am wondering what is the cause of this error. 
It's worth noting that I have not pre-normalized the data inside of the numpy arrays to be inputed.
I'm also attaching the numpy arrays in the following screenshots in order to make sure that they're in the right form.
Their shapes are: 
(3682, 120, 4)
(3682, 5)
(3682, 120)

![Screenshot (406)](https://user-images.githubusercontent.com/125367895/221363259-717282ca-15dd-4e3c-ad6b-697b76c5a653.png)
![Screenshot (407)](https://user-images.githubusercontent.com/125367895/221363272-d5b48752-5bad-4e97-ae1a-bd074867b076.png)
![Screenshot (408)](https://user-images.githubusercontent.com/125367895/221363279-8d043cf4-aa72-4ffa-9808-97ce7ac81454.png)

Thank you!

**Comment by fjxmlzn** [comment]
Could you please provide the content inside "data_feature_output.pkl" that you prepared?

**Comment by dgtriantis** [comment]
Thanks a lot for the quick response, much appreciated! Turns out there was a minor mistake in the pickle file. It runs now!

I am also having a little trouble with the training as the following error occurs: 

"Failed to create a NewWriteableFile: ./test/checkpoint\epoch_id-4\model-179.data-00000-of-00001.tempstate10424354672339237629 : The system cannot find the path specified."

I checked what was said here (https://github.com/fjxmlzn/DoppelGANger/issues/30) and I tried out the solution of [chameleonzz](https://github.com/chameleonzz) but it caused problems in the following generation of data.

I see that you provided a possible solution in the case where the GPUTaskScheduler is used. I wonder if you could provide a solution to the said problem when using the example training WITHOUT the GPUTaskScheduler. 

Thanks again!

**Comment by fjxmlzn** [comment]
I just merged the fixes from the master branch to TF2 branch. Can you re-download the code and try again? Thanks!

**Comment by dgtriantis** [comment]
I am getting the following error:

![Screenshot (410)](https://user-images.githubusercontent.com/125367895/221555343-e19eee36-0398-4fc9-a173-dee9e5ebd895.png)

**Comment by dgtriantis** [comment]
After the changes you made it runs, thanks! 

When generating samples, I am running in two problems: 
1. The same as https://github.com/fjxmlzn/DoppelGANger/issues/28
Do you have any input on this?

2. The results are not logical, all attributes have 0 or 1 value and the features do not seem to have the required behavior.
What could I do about that? Would running the training for more epochs and a lower sample_len help?

Again thank you for your help!

**Comment by fjxmlzn** [comment]
To use DoppelGANger, you will need to normalize the features into 0~1 or -1~1 and indicate the normalization method in the pkl files. From the screenshot you showed, the data is not normalized yet. It will cause problems in training.

**Comment by dgtriantis** [comment]
Ok, thank you for all the help!
