### ISSUE TITLE
Generating time series with negative values

### ISSUE THREAD

**Issue by jankrans** [fjxmlzn/DoppelGANger#39]
Hi,

I'm training a model on daily household electricty consumption. Because of solar power, negative values are present in the set. Is there any experience on how the model behaves with negative values when using the normalizing_per_sample? It seems that the model shifts the mean value to a negative value while it should be positive.

So I'm mostly wondering if their has been experience with negative values in time series, or if I rather should try to make everything positive and apply some post-processing after wards on the samples.

**Comment by fjxmlzn** [comment]
Negative values are not a problem. Before using DoppelGANger, you will need to normalize the values manually to -1~1 or 0~1, and indicate the normalization method you used in the "normalization" field in the PKL files. The generated data will be in the specified range, and you can manually re-normalize the data back to the original range. 

`normalizing_per_sample` (controlled by `self_norm` flat) can be helpful when your data has very diverse ranges across samples (see Section 4.2 of the paper). I would suggest starting without enabling this feature. If it does not work well, then you can try enabling it.

**Comment by fjxmlzn** [comment]
Feel free to re-open the issue if you still have issues with it.

**Comment by jankrans** [comment]
Thank you for the quick response! I was wondering if you maybe could provide some more info about the metrics being tracked during training, still trying to learn everything about GANs etc.. I'm trying to interpret them with tensorboard, but trying to get a good grip on wich run is good or bad, is somewhat difficult for me...

Here are two pictures of the first two trainings (so improvements have to be made)
![image](https://user-images.githubusercontent.com/98169709/221868061-a39e6e06-2d3e-43e6-8b5a-a01c825a5bd2.png)

![image](https://user-images.githubusercontent.com/98169709/221868205-b4e8908d-dc54-44b8-b2e6-f2bfdd9e2601.png)

Should some converge to 0, or should everything become as low as possible, even the graphs with negative values? These are some questions I was wondering about...

If you feel like answering maybe with a mail, which might be more appropriate, you can do so at jan.kranzen@gmail.com

**Comment by fjxmlzn** [comment]
In GANs, it is generally hard to read the sample quality from the loss. The most useful things here are `d/gp` and `attr_d/gp`:  we want them to be stable and close to 0 throughout the training. If they suddenly go to very large values (e.g., > 10), that usually means the training goes to an unstable stage and the sample quality during that stage will usually be bad. It might or might not recover itself after that stage. You can see more information about these losses we are using here in this paper: https://arxiv.org/pdf/1704.00028.pdf
