### ISSUE TITLE
is_gen_flag

### ISSUE THREAD

**Issue by Murmur0** [fjxmlzn/DoppelGANger#40]
Thanks for your great efforts and achievements in DGAN!
And I do hope that you can answer my question below.
"Note that is_gen_flag should always set to False (default). is_gen_flag=True is for internal use only (see comments in doppelganger.py for details)."
Does it mean that I cannot set the "is_gen_flag" to True?And I must choose a apporpriate length of timesteps for my examples?
Looking forward to your reply!

**Comment by fjxmlzn** [comment]
Yes. In the PKL files you provided to DoppelGANger, `is_gen_flag` should be False. The length of each time series is specified by `data_gen_flag`. The maximum length of all time series is specified by the second dimension of the shape of `data_feature` and `data_gen_flag` in `data_train.npz`. 

Does that answer your questions?

**Comment by Murmur0** [comment]
Oh,thanks for your prompt and elaborate reply!Does it mean that I can set the **data_gen_flag** to control which timestep of my example can be activated?

**Comment by fjxmlzn** [comment]
Yes

**Comment by Murmur0** [comment]
Thanks!
