### ISSUE TITLE
unknown output type

### ISSUE THREAD

**Issue by Murmur0** [fjxmlzn/DoppelGANger#45]
Hello, thanks for your works which could perfectly satisfy my research request! But I have encountered a minor problem, may in my **"data_feature_output.pkl"** , because the"worker_generate_data" told me that:

 File "D:\Anaconda\pythonProject14\DoppelGANger-TF2\example_generating_data\gan\network.py", line 262, in build
    raise Exception("unknown output type")
Exception: unknown output type

I wonder how to solve it?

My code for writing data_feature_output is following:

![image](https://github.com/fjxmlzn/DoppelGANger/assets/119090366/423e4fa1-e163-49d4-b1e6-a6ad7afcba03)

**Comment by fjxmlzn** [comment]
Do you have a duplicate [output.py](https://github.com/fjxmlzn/DoppelGANger/blob/master/gan/output.py) file in your folders? It could be that the data and network.py are loading from different output.py files.

**Comment by Murmur0** [comment]
> 

No, under "example_generating_data", there is only one "output.py".
And is there anything wrong with my codes to write the "data_feature_output"?
Actually, at the beginning to write it, Pycharm could not realize the objection "CONTINUOUS" and "ZERO-ONE" at once, so I added the path.

**Comment by Murmur0** [comment]
Here are my folds:
![image](https://github.com/fjxmlzn/DoppelGANger/assets/119090366/a8bbc17a-5b7f-4b59-b93c-1b894cf3ca3f)

**Comment by Murmur0** [comment]
On! It occurs me that I havn't used your training data to see if there is anything wrong, I just ever have used it in"example_trianing", and it could run correctly and product some picutures in examples.
But when I use "example_generating_data", I will get faults like this:
"
Not found ..\results\aux_disc-False,dataset-FCC_MBA,epoch-17000,epoch_checkpoint_freq-70,extra_checkpoint_freq-850,run-2,sample_len-8,self_norm-False,\checkpoint\epoch_id-16999
[0m
"
And after a few minutes, the program will end.

**Comment by fjxmlzn** [comment]
Did you run example_training or put the checkpoint in that path before running it? This error says that it cannot find this checkpoint path.

**Comment by fjxmlzn** [comment]
Close the issue for now since it has been a while. If you still have any problems with it, feel free to reopen the issue.
