### ISSUE TITLE
about mode-collapse

### ISSUE THREAD

**Issue by patricxu** [fjxmlzn/DoppelGANger#8]
Thanks for your work!
I have noticed in the code that you tried to mitigate mode-collapse by packing, but the num_packing is 1 by default. Do you mean packing is unnessary in this case?

**Comment by fjxmlzn** [comment]
Packing does help, but empirically we find that auto-normalization (Section 4.2 in the paper, controlled by `self_norm ` parameter) is more effective in these settings and auto-normalization itself is sufficient for giving good results, so we set num_packing to 1 (i.e. turn off it) for the results in the paper and in the default parameters.
