### ISSUE TITLE
sample_len and sample_time

### ISSUE THREAD

**Issue by patricxu** [fjxmlzn/DoppelGANger#9]
Get confused by the meaning of the variables. 

sample_len: The time series batch size.
self.sample_time = int(self.data_feature.shape[1] / self.sample_len)

In my view: 
data_feature.shape[1]: the length(steps) of the time series of a training sample. and it's fixed value for all the sample.
so the sample_time should be 0 <= sample_time < data_features.shape[1]

Did I misunderstand?

**Comment by fjxmlzn** [comment]
Sorry, the variable names are kind of confusing.

data_feature.shape[1]: You are correct.
sample_len: The time series batch size, i.e. the number of time steps generated at each RNN rollout (parameter S in Section 4.1 in the paper).
sample_time: The maximum number of RNN rollouts needed for generating a sample.

**Comment by patricxu** [comment]
Thank you!
